[package]
name = "tf-l0-codegen-rs"
version = "0.1.0"
edition = "2021"
description = "Rust pipeline scaffolding generator"
license = "MIT OR Apache-2.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
