[package]
name = "{{package_name}}"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Generated TF pipeline"

[lib]
path = "src/lib.rs"

[[bin]]
name = "run"
path = "src/run.rs"

[dependencies]
anyhow = "1"
serde_json = "1"
sha2 = "0.10"
hex = "0.4"
