name: scripts-hygiene
on: [push, pull_request]
jobs:
  check:
    if: ${{ github.ref != 'refs/heads/T1_1/run-LOCAL-FINAL' && github.head_ref != 'T1_1/run-LOCAL-FINAL' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Skip in act
        if: ${{ env.ACT }}
        run: echo "Skipping scripts hygiene under act"
      - name: Ensure scripts/ contains only approved stubs
        if: ${{ !env.ACT }}
        run: |
          set -euo pipefail
          if [ ! -d scripts ]; then
            echo "OK: scripts/ missing"
            exit 0
          fi
          allowed="check-ambient-stubs.sh oracle-core-results validate-tf-spec"
          unexpected=0
          while IFS= read -r file; do
            name=$(basename "$file")
            case " $allowed " in
              *" $name "*) ;;
              *)
                echo "Unexpected file in scripts/: $name" >&2
                unexpected=1
                ;;
            esac
          done < <(find scripts -maxdepth 1 -type f)
          if [ "$unexpected" -eq 1 ]; then
            exit 1
          fi
          echo "OK: scripts/ only contains approved stubs"
