name: t1-oracles-epic
on: [push, pull_request]
jobs:
  t1:
    strategy:
      matrix:
        job: ["oracle-core", "determinism-oracle", "conservation-oracle", "idempotence-oracle", "transport-region-oracle", "conservativity-oracle", "oracle-harness", "oracle-strength"]
        runtime: ["ts", "rust"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TypeScript runtime
        if: ${{ matrix.runtime == 'ts' }}
        uses: ./.github/actions/setup-ts
      - name: Setup Rust runtime
        if: ${{ matrix.runtime == 'rust' }}
        uses: ./.github/actions/setup-rust
      - name: Run ${{ matrix.job }}
        run: pnpm nx run ci:${{ matrix.job }} --runtime=${{ matrix.runtime }}
      - name: Determinism re-run
        run: pnpm -w tf-meta determinism --job ${{ matrix.job }} --repeats 2
      - name: Upload T1 artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: t1-${{ matrix.job }}-${{ matrix.runtime }}
          path: out/t1/**
