# .github/actions/setup-pnpm/action.yml
name: setup-pnpm
description: Setup Node + pnpm (uses version from package.json "packageManager"), optional install
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '20'
  install:
    description: Run pnpm install after setup
    required: false
    default: 'true'
  frozen:
    description: Use --frozen-lockfile when installing
    required: false
    default: 'true'
  cache-dependency-path:
    description: Path(s) to pnpm-lock.yaml for caching (supports globs)
    required: false
    default: '**/pnpm-lock.yaml'

runs:
  using: "composite"
  steps:
    # 1) Node
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs['node-version'] }}
        cache: pnpm
        cache-dependency-path: ${{ inputs['cache-dependency-path'] }}

    # 2) Install pnpm (reads version from package.json: "packageManager": "pnpm@x.y.z")
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    # 3) Sanity check
    - shell: bash
      run: |
        echo "PATH=$PATH"
        node -v
        pnpm -v
        which pnpm || true
        command -v pnpm || true

    # 4) Optional install
    - if: ${{ inputs.install == 'true' }}
      shell: bash
      run: |
        if [[ "${{ inputs.frozen }}" == "true" ]]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
