name: agents
on: [push, pull_request]
jobs:
  sync-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: |
          YQ_VERSION=v4.44.3
          sudo curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version
      - name: Verify AGENTS.md is in sync
        run: bash .codex/scripts/sync-agents.sh --check
