
name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ts:
    name: TypeScript build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tf-lang-l0-ts
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: pnpm i --frozen-lockfile=false
      - run: pnpm test

  rust:
    name: Rust build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tf-lang-l0-rs
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential pkg-config libssl-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - run: $HOME/.cargo/bin/cargo build --verbose
      - run: $HOME/.cargo/bin/cargo test --verbose

  docker:
    name: Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - id: build1
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/claims-api-ts/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/claims-api:0.2
            ghcr.io/${{ github.repository_owner }}/claims-api:latest
          push: false
          load: true
          provenance: false
          sbom: false

      - id: build2
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/claims-api-ts/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/claims-api:0.2
            ghcr.io/${{ github.repository_owner }}/claims-api:latest
          push: false
          load: true
          provenance: false
          sbom: false

      - name: Verify reproducible digest
        run: test "${{ steps.build1.outputs.digest }}" = "${{ steps.build2.outputs.digest }}"

      - uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/claims-api:0.2
          docker push ghcr.io/${{ github.repository_owner }}/claims-api:latest

      - name: Record digest
        if: github.ref == 'refs/heads/main'
        run: echo "${{ steps.build2.outputs.digest }}" >> "$GITHUB_STEP_SUMMARY"
