name: ci-fast

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      ts_changed: ${{ steps.ts.outputs.any_changed }}
      rust_changed: ${{ steps.rust.outputs.any_changed }}
      golden_changed: ${{ steps.golden.outputs.any_changed }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with: { fetch-depth: 0 }
      - id: ts
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with: { since_last_remote_commit: true, files: "packages/tf-lang-l0-ts/**" }
      - id: rust
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with: { since_last_remote_commit: true, files: "packages/tf-lang-l0-rs/**" }
      - id: golden
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c # v45
        with:
          since_last_remote_commit: true
          files: |
            packages/claims-core-ts/**
            packages/adapter-legal-ts/**
            docs/data/**
            .golden/**

  ts:
    needs: changed
    if: needs.changed.outputs.ts_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: packages/tf-lang-l0-ts } }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: pnpm i --frozen-lockfile=false
      - run: pnpm test

  rust:
    needs: changed
    if: needs.changed.outputs.rust_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: packages/tf-lang-l0-rs } }
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential pkg-config libssl-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
      - run: $HOME/.cargo/bin/cargo build --verbose
      - run: $HOME/.cargo/bin/cargo test --verbose

  golden:
    needs: changed
    if: needs.changed.outputs.golden_changed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: pnpm i --frozen-lockfile=false
      - run: pnpm -C packages/claims-core-ts build
      - run: pnpm -C packages/adapter-legal-ts build
      - name: Golden diff
        run: |
          node packages/adapter-legal-ts/dist/examples/ro-mini/build.js > /tmp/ro-mini.out.txt
          diff -u .golden/ro-mini.out.txt /tmp/ro-mini.out.txt
