name: Conformance (TS ↔ Rust)

on:
  push:
    branches: [main]
    paths:
      - 'packages/tf-lang-l0-ts/**'
      - 'packages/tf-lang-l0-rs/**'
      - 'packages/tf-trace/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/tf-lang-l0-ts/**'
      - 'packages/tf-lang-l0-rs/**'
      - 'packages/tf-trace/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pnpm-lock.yaml'

jobs:
  conformance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'
          frozen: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'merge_group' }}

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            packages/tf-lang-l0-rs/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('packages/tf-lang-l0-rs/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Lint vectors (schema sanity)
        run: node .codex/scripts/lint-vectors.mjs

      - name: Build TS kernel
        run: pnpm -C packages/tf-lang-l0-ts build
      - name: Build tf-trace (required by fast tests)
        run: pnpm -C packages/tf-trace build

      - name: Parity tests
        run: pnpm run test:parity

      - name: Run TS vectors
        run: pnpm -C packages/tf-lang-l0-ts vectors

      - name: Upload TS report
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: ts-report
          path: tests/vectors/.out/ts-report.json

      - name: Cargo tests (includes vectors)
        run: cargo test --manifest-path packages/tf-lang-l0-rs/Cargo.toml --tests -- --nocapture

      - name: Upload RS report
        if: ${{ always() && !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: rs-report
          path: tests/vectors/.out/rs-report.json

      - name: Upload test manifests
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: conformance-tests
          path: out/0.4/tests/**

      - name: Cross-compare TS vs RS reports
        run: node .codex/scripts/compare-reports.mjs

      - name: Print reports on failure
        if: failure()
        run: |
          echo '--- ts-report ---'
          if [ -f tests/vectors/.out/ts-report.json ]; then
            cat tests/vectors/.out/ts-report.json
          else
            echo 'ts-report missing'
          fi
          echo '--- rs-report ---'
          if [ -f tests/vectors/.out/rs-report.json ]; then
            cat tests/vectors/.out/rs-report.json
          else
            echo 'rs-report missing'
          fi
