name: ghcr

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/claims-api-ts
      SOURCE_DATE_EPOCH: 0
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/claims-api-ts/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:0.2,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          provenance: false

      - name: Rebuild to verify reproducibility
        id: rebuild
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/claims-api-ts/Dockerfile
          platforms: linux/amd64
          push: false
          provenance: false

      - name: Confirm reproducible digest
        run: |
          if [ "${{ steps.build.outputs.digest }}" != "${{ steps.rebuild.outputs.digest }}" ]; then
            echo "digests differ" >&2
            exit 1
          fi

      - name: Record digest
        run: echo "digest=${{ steps.build.outputs.digest }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Skip push notice
        if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        run: echo "PR build - image not pushed"
