name: Docs Sync

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'
          frozen: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'merge_group' }}

      - name: Install ripgrep (needed by sqlite.test.ts)
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Build (for lattice import)
        run: |
          pnpm run a0
          pnpm run a1
          pnpm -w -r build

      - name: Fast tests
        run: pnpm run test:fast

      - name: Generate docs
        run: pnpm run docs:gen

      - name: Check docs sync
        run: pnpm run docs:check

      - name: Zip docs artifact
        if: github.ref == 'refs/heads/main' && env.ACT != 'true'
        run: zip -r docs.zip docs

      - name: Upload docs artifact
        if: github.ref == 'refs/heads/main' && env.ACT != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.zip

      - name: Upload test manifests
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-tests
          path: out/0.4/tests/**
