name: L0 Proof Artifacts

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'schemas/**'
      - 'examples/**'
      - 'scripts/**'
      - 'docs/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/l0-proofs.yml'
  workflow_dispatch:

jobs:
  emit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '20'
          install: 'true'
          frozen: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'merge_group' }}
          cache-dependency-path: |
            pnpm-lock.yaml
            **/pnpm-lock.yaml

      - name: A0/A1 + build
        run: |
          pnpm run a0
          pnpm run a1
          pnpm -w -r build

      - name: Emit proof artifacts
        run: node scripts/proofs-emit-all.mjs

      - name: Run proof coverage analysis
        run: |
          node scripts/proofs/coverage.mjs
          node scripts/proofs/emit-missing-laws.mjs

      - name: List artifacts
        run: |
          echo "::group::proof files"
          find out/0.4/proofs -type f -print
          echo "::endgroup::"

      - name: Upload proofs (SMT + models + coverage)
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: l0-proofs
          path: out/0.4/proofs/**
