name: Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare site
        run: |
          mkdir -p site
          cat > site/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>TF-Lang</title>
          <h1>TF-Lang</h1>
          <p>GitHub Pages stub for badges/tests. See README for details.</p>
          HTML
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: github.ref == 'refs/heads/main'  # deploy only from main (tests expect this exact guard)
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
