name: pages
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch or commit) to preview'
        required: false
        default: ''
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
