name: t2-runtime

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  tf-check-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @tf-lang/tf-check run build
      - run: pnpm --filter @tf-lang/tf-check run test
      - run: pnpm --filter @tf-lang/tf-check run artifacts
      - run: |
          sha256sum out/t2/tf-check/help.txt out/t2/tf-check/result.json > out/t2/tf-check.sha
      - run: pnpm --filter @tf-lang/tf-check run artifacts
      - run: sha256sum --check out/t2/tf-check.sha
      - uses: actions/upload-artifact@v4
        with:
          name: tf-check
          path: |
            out/t2/tf-check/help.txt
            out/t2/tf-check/result.json

  adapter-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter "./packages/tf-lang-l0-ts" run build
      - run: pnpm --filter @tf-lang/adapter-execution-ts run build
      - run: pnpm --filter @tf-lang/adapter-execution-ts run test
      - run: pnpm --filter @tf-lang/adapter-execution-ts run fixtures
      - run: sha256sum out/t2/adapter-ts-trace.json > out/t2/adapter-ts-trace.json.sha
      - run: pnpm --filter @tf-lang/adapter-execution-ts run fixtures
      - run: sha256sum --check out/t2/adapter-ts-trace.json.sha
      - uses: actions/upload-artifact@v4
        with:
          name: adapter-ts
          path: out/t2/adapter-ts-trace.json

  adapter-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@3cf1046959f7ce90f2bbb139f49b41fc1acbfd4a # v2
        with:
          workspaces: crates -> crates/target
          cache-on-failure: true
      - run: cargo test --manifest-path crates/Cargo.toml --package tf-adapters-execution --all-targets

  mapper-trace2tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @tf-lang/trace2tags build
      - run: pnpm --filter @tf-lang/trace2tags run test
      - run: pnpm --filter @tf-lang/trace2tags run artifacts
      - run: sha256sum out/t2/trace-tags.json > out/t2/trace-tags.json.sha
      - run: pnpm --filter @tf-lang/trace2tags run artifacts
      - run: sha256sum --check out/t2/trace-tags.json.sha
      - uses: actions/upload-artifact@v4
        with:
          name: trace-tags
          path: out/t2/trace-tags.json

  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @tf-lang/trace2tags run artifacts
      - run: pnpm --filter @tf-lang/coverage-generator run build
      - run: pnpm --filter @tf-lang/coverage-generator run test
      - run: pnpm --filter @tf-lang/coverage-generator run artifacts
      - run: |
          sha256sum out/t2/coverage.json out/t2/coverage.html > out/t2/coverage.sha
      - run: pnpm --filter @tf-lang/coverage-generator run artifacts
      - run: sha256sum --check out/t2/coverage.sha
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            out/t2/coverage.json
            out/t2/coverage.html

  adapter-parity:
    runs-on: ubuntu-latest
    needs: [adapter-ts, adapter-rust]
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.16.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@3cf1046959f7ce90f2bbb139f49b41fc1acbfd4a # v2
        with:
          workspaces: crates -> crates/target
          cache-on-failure: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @tf-lang/adapter-execution-ts run build
      - run: pnpm --filter @tf-lang/adapter-execution-ts run parity
      - run: sha256sum out/t2/adapter-parity.json > out/t2/adapter-parity.json.sha
      - run: pnpm --filter @tf-lang/adapter-execution-ts run parity
      - run: sha256sum --check out/t2/adapter-parity.json.sha
      - uses: actions/upload-artifact@v4
        with:
          name: adapter-parity
          path: out/t2/adapter-parity.json
